import React from 'react';
import { AlertTriangle } from 'lucide-react';

export const Footer: React.FC = () => {
  return (
    <footer className="mt-auto py-8 bg-slate-50 border-t border-slate-200">
      <div className="max-w-3xl mx-auto px-4">
        <div className="bg-amber-50 border border-amber-200 rounded-xl p-4 flex flex-col sm:flex-row gap-4 items-start">
          <div className="bg-amber-100 p-2 rounded-full shrink-0">
            <AlertTriangle className="w-5 h-5 text-amber-600" />
          </div>
          <div>
            <h4 className="font-bold text-amber-900 text-sm uppercase tracking-wide mb-1">
              Medical Disclaimer
            </h4>
            <p className="text-amber-800 text-sm leading-relaxed">
              HexaCare Vision is an <strong>educational screening tool</strong> and does not provide medical diagnoses. 
              The results generated by this AI system are preliminary and may be inaccurate. 
              Always consult a certified dermatologist or medical professional for proper diagnosis and treatment.
              Do not disregard professional medical advice based on these results.
            </p>
          </div>
        </div>
        <div className="text-center mt-6 text-slate-400 text-xs">
          &copy; {new Date().getFullYear()} HexaCare Intelligence. All rights reserved.
        </div>
      </div>
    </footer>
  );
};